name: create and push alpine_ffmpeg

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io
  
jobs:
  docker-ghcr-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4          
    - name: Log in to the Container registry
      uses: docker/login-action@v3.2.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: |
          ghcr.io/${{ github.repository }}/alpine_ffmpeg
        tags: |
          latest
          
    - name: Build and push
      uses: docker/build-push-action@v5.4.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
